#testing
name: test
on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*
      - hotfix/v*
      - master
  push:
    branches:
      - develop
      - master
      - release/v*
      - hotfix/v*

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          exit 1
          
      - name: Update status of branch
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          state: ${{ job.status }}
